version: '3.4'

services:
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - '27017:27017'
    networks:
      - appnet
    volumes:
      - "mongo-data:/data/db"

networks:
  appnet:
    driver: bridge

volumes:
  mongo-data: