FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ARG pipelineId=0

WORKDIR /Gitbulker.Web
RUN dotnet restore Sgm.Api.csproj -v q \
    && dotnet publish -v q -c Release -o /app /property:InformationalVersion=$pipelineId

WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Gitbulker.Web.dll"]
